import { PageMetadata } from '@/contents/projectsContents';
import { Document as LGCDocument } from 'langchain/document';

export const bucket1: LGCDocument<PageMetadata>[] = [
  {
    pageContent:
      'Avalanche, a layer 1 blockchain network, has achieved a significant milestone by surpassing 1 million monthly active users for the first time. This remarkable growth can be attributed to the recent introduction of AvaCloud, which has been highlighted as the primary catalyst by Ava Labs, the creator of Avalanche. AvaCloud is a user-friendly platform that allows for the creation of "custom blockchains," also known as subnets, on the Avalanche network. Numerous projects, including the Korean conglomerate SK Group, gaming app Blitz, and AAA game studio Shrapnel, have already committed to developing subnets using AvaCloud. Additionally, Circle, the issuer of the second-largest stablecoin USDC, recently announced the native availability of their Euro-backed stablecoin, EuroC, on the Avalanche network. Alibaba\'s cloud division has also developed a launchpad enabling businesses to deploy metaverse spaces on the Avalanche blockchain. As of now, Avalanche stands as the seventh largest blockchain network, with a total value locked (TVL) of approximately $700 million.',
    metadata: {
      chunk:
        'Avalanche, a layer 1 blockchain network, has achieved a significant milestone by surpassing 1 million monthly active users for the first time. This remarkable growth can be attributed to the recent introduction of AvaCloud, which has been highlighted as the primary catalyst by Ava Labs, the creator of Avalanche. AvaCloud is a user-friendly platform that allows for the creation of "custom blockchains," also known as subnets, on the Avalanche network. Numerous projects, including the Korean conglomerate SK Group, gaming app Blitz, and AAA game studio Shrapnel, have already committed to developing subnets using AvaCloud. Additionally, Circle, the issuer of the second-largest stablecoin USDC, recently announced the native availability of their Euro-backed stablecoin, EuroC, on the Avalanche network. Alibaba\'s cloud division has also developed a launchpad enabling businesses to deploy metaverse spaces on the Avalanche blockchain. As of now, Avalanche stands as the seventh largest blockchain network, with a total value locked (TVL) of approximately $700 million.',
      text: 'Avalanche, a layer 1 blockchain network, has achieved a significant milestone by surpassing 1 million monthly active users for the first time. This remarkable growth can be attributed to the recent introduction of AvaCloud, which has been highlighted as the primary catalyst by Ava Labs, the creator of Avalanche. AvaCloud is a user-friendly platform that allows for the creation of "custom blockchains," also known as subnets, on the Avalanche network. Numerous projects, including the Korean conglomerate SK Group, gaming app Blitz, and AAA game studio Shrapnel, have already committed to developing subnets using AvaCloud. Additionally, Circle, the issuer of the second-largest stablecoin USDC, recently announced the native availability of their Euro-backed stablecoin, EuroC, on the Avalanche network. Alibaba\'s cloud division has also developed a launchpad enabling businesses to deploy metaverse spaces on the Avalanche blockchain. As of now, Avalanche stands as the seventh largest blockchain network, with a total value locked (TVL) of approximately $700 million.',
      url: 'https://www.theblock.co/post/232881/avalanche-avax-1-million-mau',
    },
  },
  {
    pageContent:
      'avalanche, a layer 1 blockchain network, has crossed 1 million monthly active users for the first time. the recent launch of avacloud is the main reason for the growth, according to ava labs, the creator of avalanche. avacloud is a no-code platform for launching "custom blockchains," also known as subnets, on top of the avalanche network. several projects have committed to building subnets via avacloud, including korean conglomerate sk group, gaming app blitz, and aaa game studio shrapnel. circle, the issuer of the second-largest stablecoin usdc, announced recently that its euro-backed stablecoin euroc is now natively available on avalanche. alibaba\'s cloud division also built a launchpad for businesses to deploy metaverse spaces on the avalanche blockchain. avalanche is currently the seventh largest blockchain network with a total value locked or tvl of around $700 million.',
    metadata: {
      chunk:
        'avalanche, a layer 1 blockchain network, has crossed 1 million monthly active users for the first time. the recent launch of avacloud is the main reason for the growth, according to ava labs, the creator of avalanche. avacloud is a no-code platform for launching "custom blockchains," also known as subnets, on top of the avalanche network. several projects have committed to building subnets via avacloud, including korean conglomerate sk group, gaming app blitz, and aaa game studio shrapnel. circle, the issuer of the second-largest stablecoin usdc, announced recently that its euro-backed stablecoin euroc is now natively available on avalanche. alibaba\'s cloud division also built a launchpad for businesses to deploy metaverse spaces on the avalanche blockchain. avalanche is currently the seventh largest blockchain network with a total value locked or tvl of around $700 million.',
      text: 'avalanche, a layer 1 blockchain network, has crossed 1 million monthly active users for the first time. the recent launch of avacloud is the main reason for the growth, according to ava labs, the creator of avalanche. avacloud is a no-code platform for launching "custom blockchains," also known as subnets, on top of the avalanche network. several projects have committed to building subnets via avacloud, including korean conglomerate sk group, gaming app blitz, and aaa game studio shrapnel. circle, the issuer of the second-largest stablecoin usdc, announced recently that its euro-backed stablecoin euroc is now natively available on avalanche. alibaba\'s cloud division also built a launchpad for businesses to deploy metaverse spaces on the avalanche blockchain. avalanche is currently the seventh largest blockchain network with a total value locked or tvl of around $700 million.',
      url: 'https://www.theblock.co/post/232881/avalanche-avax-1-million-mau',
    },
  },
  {
    pageContent:
      'avalanche, a layer 1 blockchain network, has crossed 1 million monthly active users for the first time. the recent launch of avacloud is the main reason for the growth, according to ava labs, the creator of avalanche. avacloud is a no-code platform for launching "custom blockchains," also known as subnets, on top of the avalanche network. several projects have committed to building subnets via avacloud, including korean conglomerate sk group, gaming app blitz, and aaa game studio shrapnel. circle, the issuer of the second-largest stablecoin usdc, announced recently that its euro-backed stablecoin euroc is now natively available on avalanche. alibaba\'s cloud division also built a launchpad for businesses to deploy metaverse spaces on the avalanche blockchain. avalanche is currently the seventh largest blockchain network with a total value locked or tvl of around $700 million.',
    metadata: {
      chunk:
        'avalanche, a layer 1 blockchain network, has crossed 1 million monthly active users for the first time. the recent launch of avacloud is the main reason for the growth, according to ava labs, the creator of avalanche. avacloud is a no-code platform for launching "custom blockchains," also known as subnets, on top of the avalanche network. several projects have committed to building subnets via avacloud, including korean conglomerate sk group, gaming app blitz, and aaa game studio shrapnel. circle, the issuer of the second-largest stablecoin usdc, announced recently that its euro-backed stablecoin euroc is now natively available on avalanche. alibaba\'s cloud division also built a launchpad for businesses to deploy metaverse spaces on the avalanche blockchain. avalanche is currently the seventh largest blockchain network with a total value locked or tvl of around $700 million.',
      text: 'avalanche, a layer 1 blockchain network, has crossed 1 million monthly active users for the first time. the recent launch of avacloud is the main reason for the growth, according to ava labs, the creator of avalanche. avacloud is a no-code platform for launching "custom blockchains," also known as subnets, on top of the avalanche network. several projects have committed to building subnets via avacloud, including korean conglomerate sk group, gaming app blitz, and aaa game studio shrapnel. circle, the issuer of the second-largest stablecoin usdc, announced recently that its euro-backed stablecoin euroc is now natively available on avalanche. alibaba\'s cloud division also built a launchpad for businesses to deploy metaverse spaces on the avalanche blockchain. avalanche is currently the seventh largest blockchain network with a total value locked or tvl of around $700 million.',
      url: 'https://www.theblock.co/post/232881/avalanche-avax-1-million-mau',
    },
  },
  {
    pageContent:
      'avalanche, a layer 1 blockchain network, has crossed 1 million monthly active users for the first time. the recent launch of avacloud is the main reason for the growth, according to ava labs, the creator of avalanche. avacloud is a no-code platform for launching "custom blockchains," also known as subnets, on top of the avalanche network. several projects have committed to building subnets via avacloud, including korean conglomerate sk group, gaming app blitz, and aaa game studio shrapnel. circle, the issuer of the second-largest stablecoin usdc, announced recently that its euro-backed stablecoin euroc is now natively available on avalanche. alibaba\'s cloud division also built a launchpad for businesses to deploy metaverse spaces on the avalanche blockchain. avalanche is currently the seventh largest blockchain network with a total value locked or tvl of around $700 million.',
    metadata: {
      chunk:
        'avalanche, a layer 1 blockchain network, has crossed 1 million monthly active users for the first time. the recent launch of avacloud is the main reason for the growth, according to ava labs, the creator of avalanche. avacloud is a no-code platform for launching "custom blockchains," also known as subnets, on top of the avalanche network. several projects have committed to building subnets via avacloud, including korean conglomerate sk group, gaming app blitz, and aaa game studio shrapnel. circle, the issuer of the second-largest stablecoin usdc, announced recently that its euro-backed stablecoin euroc is now natively available on avalanche. alibaba\'s cloud division also built a launchpad for businesses to deploy metaverse spaces on the avalanche blockchain. avalanche is currently the seventh largest blockchain network with a total value locked or tvl of around $700 million.',
      text: 'avalanche, a layer 1 blockchain network, has crossed 1 million monthly active users for the first time. the recent launch of avacloud is the main reason for the growth, according to ava labs, the creator of avalanche. avacloud is a no-code platform for launching "custom blockchains," also known as subnets, on top of the avalanche network. several projects have committed to building subnets via avacloud, including korean conglomerate sk group, gaming app blitz, and aaa game studio shrapnel. circle, the issuer of the second-largest stablecoin usdc, announced recently that its euro-backed stablecoin euroc is now natively available on avalanche. alibaba\'s cloud division also built a launchpad for businesses to deploy metaverse spaces on the avalanche blockchain. avalanche is currently the seventh largest blockchain network with a total value locked or tvl of around $700 million.',
      url: 'https://www.theblock.co/post/232881/avalanche-avax-1-million-mau',
    },
  },
  {
    pageContent:
      'avalanche (avax) has reached a milestone of one million monthly active users (mau) about a week after the launch of avacloud platform, its innovative cloud computing service. ava labs, the creator of avalanche, believes the launch of avacloud has played a crucial role in the rapid growth of avalanche’s user base. avacloud is a no-code outfit that enables the creation and launch of “custom blockchains” on top of the avalanche network. several projects have committed to building subnets via avacloud, highlighting the growing recognition and adoption of avalanche’s customizable blockchain solutions across diverse industries. with one million monthly active users, the protocol has demonstrated its ability to handle a significant load of transactions and interactions on its network. looking ahead, the blockchain network’s rapid growth and expanding user base suggests a promising future for the platform as more developers and consumers discover the benefits of avalanche’s technology.',
    metadata: {
      chunk:
        'avalanche (avax) has reached a milestone of one million monthly active users (mau) about a week after the launch of avacloud platform, its innovative cloud computing service. ava labs, the creator of avalanche, believes the launch of avacloud has played a crucial role in the rapid growth of avalanche’s user base. avacloud is a no-code outfit that enables the creation and launch of “custom blockchains” on top of the avalanche network. several projects have committed to building subnets via avacloud, highlighting the growing recognition and adoption of avalanche’s customizable blockchain solutions across diverse industries. with one million monthly active users, the protocol has demonstrated its ability to handle a significant load of transactions and interactions on its network. looking ahead, the blockchain network’s rapid growth and expanding user base suggests a promising future for the platform as more developers and consumers discover the benefits of avalanche’s technology.',
      text: 'avalanche (avax) has reached a milestone of one million monthly active users (mau) about a week after the launch of avacloud platform, its innovative cloud computing service. ava labs, the creator of avalanche, believes the launch of avacloud has played a crucial role in the rapid growth of avalanche’s user base. avacloud is a no-code outfit that enables the creation and launch of “custom blockchains” on top of the avalanche network. several projects have committed to building subnets via avacloud, highlighting the growing recognition and adoption of avalanche’s customizable blockchain solutions across diverse industries. with one million monthly active users, the protocol has demonstrated its ability to handle a significant load of transactions and interactions on its network. looking ahead, the blockchain network’s rapid growth and expanding user base suggests a promising future for the platform as more developers and consumers discover the benefits of avalanche’s technology.',
      url: 'https://coingape.com/avalanche-hits-1m-monthly-active-users-a-week-after-avacloud-went-live/',
    },
  },
  {
    pageContent:
      'avalanche (avax) has reached a milestone of one million monthly active users (mau) about a week after the launch of avacloud platform, its innovative cloud computing service. ava labs, the creator of avalanche, believes the launch of avacloud has played a crucial role in the rapid growth of avalanche’s user base. avacloud is a no-code outfit that enables the creation and launch of “custom blockchains” on top of the avalanche network. several projects have committed to building subnets via avacloud, highlighting the growing recognition and adoption of avalanche’s customizable blockchain solutions across diverse industries. with one million monthly active users, the protocol has demonstrated its ability to handle a significant load of transactions and interactions on its network. looking ahead, the blockchain network’s rapid growth and expanding user base suggests a promising future for the platform as more developers and consumers discover the benefits of avalanche’s technology.',
    metadata: {
      chunk:
        'avalanche (avax) has reached a milestone of one million monthly active users (mau) about a week after the launch of avacloud platform, its innovative cloud computing service. ava labs, the creator of avalanche, believes the launch of avacloud has played a crucial role in the rapid growth of avalanche’s user base. avacloud is a no-code outfit that enables the creation and launch of “custom blockchains” on top of the avalanche network. several projects have committed to building subnets via avacloud, highlighting the growing recognition and adoption of avalanche’s customizable blockchain solutions across diverse industries. with one million monthly active users, the protocol has demonstrated its ability to handle a significant load of transactions and interactions on its network. looking ahead, the blockchain network’s rapid growth and expanding user base suggests a promising future for the platform as more developers and consumers discover the benefits of avalanche’s technology.',
      text: 'avalanche (avax) has reached a milestone of one million monthly active users (mau) about a week after the launch of avacloud platform, its innovative cloud computing service. ava labs, the creator of avalanche, believes the launch of avacloud has played a crucial role in the rapid growth of avalanche’s user base. avacloud is a no-code outfit that enables the creation and launch of “custom blockchains” on top of the avalanche network. several projects have committed to building subnets via avacloud, highlighting the growing recognition and adoption of avalanche’s customizable blockchain solutions across diverse industries. with one million monthly active users, the protocol has demonstrated its ability to handle a significant load of transactions and interactions on its network. looking ahead, the blockchain network’s rapid growth and expanding user base suggests a promising future for the platform as more developers and consumers discover the benefits of avalanche’s technology.',
      url: 'https://coingape.com/avalanche-hits-1m-monthly-active-users-a-week-after-avacloud-went-live/',
    },
  },
  {
    pageContent:
      'avalanche (avax) has reached a milestone of one million monthly active users (mau) about a week after the launch of avacloud platform, its innovative cloud computing service. ava labs, the creator of avalanche, believes the launch of avacloud has played a crucial role in the rapid growth of avalanche’s user base. avacloud is a no-code outfit that enables the creation and launch of “custom blockchains” on top of the avalanche network. several projects have committed to building subnets via avacloud, highlighting the growing recognition and adoption of avalanche’s customizable blockchain solutions across diverse industries. with one million monthly active users, the protocol has demonstrated its ability to handle a significant load of transactions and interactions on its network. looking ahead, the blockchain network’s rapid growth and expanding user base suggests a promising future for the platform as more developers and consumers discover the benefits of avalanche’s technology.',
    metadata: {
      chunk:
        'avalanche (avax) has reached a milestone of one million monthly active users (mau) about a week after the launch of avacloud platform, its innovative cloud computing service. ava labs, the creator of avalanche, believes the launch of avacloud has played a crucial role in the rapid growth of avalanche’s user base. avacloud is a no-code outfit that enables the creation and launch of “custom blockchains” on top of the avalanche network. several projects have committed to building subnets via avacloud, highlighting the growing recognition and adoption of avalanche’s customizable blockchain solutions across diverse industries. with one million monthly active users, the protocol has demonstrated its ability to handle a significant load of transactions and interactions on its network. looking ahead, the blockchain network’s rapid growth and expanding user base suggests a promising future for the platform as more developers and consumers discover the benefits of avalanche’s technology.',
      text: 'avalanche (avax) has reached a milestone of one million monthly active users (mau) about a week after the launch of avacloud platform, its innovative cloud computing service. ava labs, the creator of avalanche, believes the launch of avacloud has played a crucial role in the rapid growth of avalanche’s user base. avacloud is a no-code outfit that enables the creation and launch of “custom blockchains” on top of the avalanche network. several projects have committed to building subnets via avacloud, highlighting the growing recognition and adoption of avalanche’s customizable blockchain solutions across diverse industries. with one million monthly active users, the protocol has demonstrated its ability to handle a significant load of transactions and interactions on its network. looking ahead, the blockchain network’s rapid growth and expanding user base suggests a promising future for the platform as more developers and consumers discover the benefits of avalanche’s technology.',
      url: 'https://coingape.com/avalanche-hits-1m-monthly-active-users-a-week-after-avacloud-went-live/',
    },
  },
];

export const bucket2: LGCDocument<PageMetadata>[] = [
  {
    pageContent:
      'european central bank president christine lagarde said in a speech thursday that it is not yet apparent that core inflation has peaked in the euro zone, signaling further hikes in interest rates in the continent. data showed inflation in the 20-nation euro zone slowed markedly last month, indicating that the toughest monetary-tightening campaign of the euro era can soon draw to a close. however, lagarde said that there is no clear evidence of that yet, signaling more rate hikes in the coming months. core price pressures indicate that there’s probably still at least one more hike to come to ensure the 2% inflation target is reached. in the united states of america, fomc will meet on 15th and 16th june to decide further interest rate hikes. analysts are expecting one more hike in the interest rates in the current cycle. jai pratap is a crypto and blockchain enthusiast with over three years of working experience with different major media houses.',
    metadata: {
      chunk:
        'european central bank president christine lagarde said in a speech thursday that it is not yet apparent that core inflation has peaked in the euro zone, signaling further hikes in interest rates in the continent. data showed inflation in the 20-nation euro zone slowed markedly last month, indicating that the toughest monetary-tightening campaign of the euro era can soon draw to a close. however, lagarde said that there is no clear evidence of that yet, signaling more rate hikes in the coming months. core price pressures indicate that there’s probably still at least one more hike to come to ensure the 2% inflation target is reached. in the united states of america, fomc will meet on 15th and 16th june to decide further interest rate hikes. analysts are expecting one more hike in the interest rates in the current cycle. jai pratap is a crypto and blockchain enthusiast with over three years of working experience with different major media houses.',
      text: 'european central bank president christine lagarde said in a speech thursday that it is not yet apparent that core inflation has peaked in the euro zone, signaling further hikes in interest rates in the continent. data showed inflation in the 20-nation euro zone slowed markedly last month, indicating that the toughest monetary-tightening campaign of the euro era can soon draw to a close. however, lagarde said that there is no clear evidence of that yet, signaling more rate hikes in the coming months. core price pressures indicate that there’s probably still at least one more hike to come to ensure the 2% inflation target is reached. in the united states of america, fomc will meet on 15th and 16th june to decide further interest rate hikes. analysts are expecting one more hike in the interest rates in the current cycle. jai pratap is a crypto and blockchain enthusiast with over three years of working experience with different major media houses.',
      url: 'https://coingape.com/european-central-bank-chief-signals-further-hikes-in-interest-rates/',
    },
  },
  {
    pageContent:
      'european central bank president christine lagarde said in a speech thursday that it is not yet apparent that core inflation has peaked in the euro zone, signaling further hikes in interest rates in the continent. data showed inflation in the 20-nation euro zone slowed markedly last month, indicating that the toughest monetary-tightening campaign of the euro era can soon draw to a close. however, lagarde said that there is no clear evidence of that yet, signaling more rate hikes in the coming months. core price pressures indicate that there’s probably still at least one more hike to come to ensure the 2% inflation target is reached. in the united states of america, fomc will meet on 15th and 16th june to decide further interest rate hikes. analysts are expecting one more hike in the interest rates in the current cycle. jai pratap is a crypto and blockchain enthusiast with over three years of working experience with different major media houses.',
    metadata: {
      chunk:
        'european central bank president christine lagarde said in a speech thursday that it is not yet apparent that core inflation has peaked in the euro zone, signaling further hikes in interest rates in the continent. data showed inflation in the 20-nation euro zone slowed markedly last month, indicating that the toughest monetary-tightening campaign of the euro era can soon draw to a close. however, lagarde said that there is no clear evidence of that yet, signaling more rate hikes in the coming months. core price pressures indicate that there’s probably still at least one more hike to come to ensure the 2% inflation target is reached. in the united states of america, fomc will meet on 15th and 16th june to decide further interest rate hikes. analysts are expecting one more hike in the interest rates in the current cycle. jai pratap is a crypto and blockchain enthusiast with over three years of working experience with different major media houses.',
      text: 'european central bank president christine lagarde said in a speech thursday that it is not yet apparent that core inflation has peaked in the euro zone, signaling further hikes in interest rates in the continent. data showed inflation in the 20-nation euro zone slowed markedly last month, indicating that the toughest monetary-tightening campaign of the euro era can soon draw to a close. however, lagarde said that there is no clear evidence of that yet, signaling more rate hikes in the coming months. core price pressures indicate that there’s probably still at least one more hike to come to ensure the 2% inflation target is reached. in the united states of america, fomc will meet on 15th and 16th june to decide further interest rate hikes. analysts are expecting one more hike in the interest rates in the current cycle. jai pratap is a crypto and blockchain enthusiast with over three years of working experience with different major media houses.',
      url: 'https://coingape.com/european-central-bank-chief-signals-further-hikes-in-interest-rates/',
    },
  },
  {
    pageContent:
      'european central bank president christine lagarde said in a speech thursday that it is not yet apparent that core inflation has peaked in the euro zone, signaling further hikes in interest rates in the continent. data showed inflation in the 20-nation euro zone slowed markedly last month, indicating that the toughest monetary-tightening campaign of the euro era can soon draw to a close. however, lagarde said that there is no clear evidence of that yet, signaling more rate hikes in the coming months. core price pressures indicate that there’s probably still at least one more hike to come to ensure the 2% inflation target is reached. in the united states of america, fomc will meet on 15th and 16th june to decide further interest rate hikes. analysts are expecting one more hike in the interest rates in the current cycle. jai pratap is a crypto and blockchain enthusiast with over three years of working experience with different major media houses.',
    metadata: {
      chunk:
        'european central bank president christine lagarde said in a speech thursday that it is not yet apparent that core inflation has peaked in the euro zone, signaling further hikes in interest rates in the continent. data showed inflation in the 20-nation euro zone slowed markedly last month, indicating that the toughest monetary-tightening campaign of the euro era can soon draw to a close. however, lagarde said that there is no clear evidence of that yet, signaling more rate hikes in the coming months. core price pressures indicate that there’s probably still at least one more hike to come to ensure the 2% inflation target is reached. in the united states of america, fomc will meet on 15th and 16th june to decide further interest rate hikes. analysts are expecting one more hike in the interest rates in the current cycle. jai pratap is a crypto and blockchain enthusiast with over three years of working experience with different major media houses.',
      text: 'european central bank president christine lagarde said in a speech thursday that it is not yet apparent that core inflation has peaked in the euro zone, signaling further hikes in interest rates in the continent. data showed inflation in the 20-nation euro zone slowed markedly last month, indicating that the toughest monetary-tightening campaign of the euro era can soon draw to a close. however, lagarde said that there is no clear evidence of that yet, signaling more rate hikes in the coming months. core price pressures indicate that there’s probably still at least one more hike to come to ensure the 2% inflation target is reached. in the united states of america, fomc will meet on 15th and 16th june to decide further interest rate hikes. analysts are expecting one more hike in the interest rates in the current cycle. jai pratap is a crypto and blockchain enthusiast with over three years of working experience with different major media houses.',
      url: 'https://coingape.com/european-central-bank-chief-signals-further-hikes-in-interest-rates/',
    },
  },
  {
    pageContent:
      'european stock markets opened higher friday morning as the us passed a bill to raise the debt ceiling and cap government spending for two years, averting a global economic catastrophe. jai pratap is a crypto and blockchain enthusiast with over three years of working experience with different major media houses. his current role at coingape includes creating high-impact web stories, cover breaking news, and write editorials. the debt ceiling bill passed the senate vote late thursday, after passing the house of representatives on wednesday. the uncertainty around the debt ceiling bill has only slightly rattled markets in the past month. now all eyes turn to the outlook for the u.s. economy, recession risk, and whether the federal reserve will raise, pause or even look at beginning to cut interest rates. european central bank president christine lagarde said inflation was still “too high” and that the hiking cycle needed to continue until it was clear inflation would come down to its 2% target in a “timely manner”. jai pratap also reads russian literature or watches some swedish movie when not working.',
    metadata: {
      chunk:
        'european stock markets opened higher friday morning as the us passed a bill to raise the debt ceiling and cap government spending for two years, averting a global economic catastrophe. jai pratap is a crypto and blockchain enthusiast with over three years of working experience with different major media houses. his current role at coingape includes creating high-impact web stories, cover breaking news, and write editorials. the debt ceiling bill passed the senate vote late thursday, after passing the house of representatives on wednesday. the uncertainty around the debt ceiling bill has only slightly rattled markets in the past month. now all eyes turn to the outlook for the u.s. economy, recession risk, and whether the federal reserve will raise, pause or even look at beginning to cut interest rates. european central bank president christine lagarde said inflation was still “too high” and that the hiking cycle needed to continue until it was clear inflation would come down to its 2% target in a “timely manner”. jai pratap also reads russian literature or watches some swedish movie when not working.',
      text: 'european stock markets opened higher friday morning as the us passed a bill to raise the debt ceiling and cap government spending for two years, averting a global economic catastrophe. jai pratap is a crypto and blockchain enthusiast with over three years of working experience with different major media houses. his current role at coingape includes creating high-impact web stories, cover breaking news, and write editorials. the debt ceiling bill passed the senate vote late thursday, after passing the house of representatives on wednesday. the uncertainty around the debt ceiling bill has only slightly rattled markets in the past month. now all eyes turn to the outlook for the u.s. economy, recession risk, and whether the federal reserve will raise, pause or even look at beginning to cut interest rates. european central bank president christine lagarde said inflation was still “too high” and that the hiking cycle needed to continue until it was clear inflation would come down to its 2% target in a “timely manner”. jai pratap also reads russian literature or watches some swedish movie when not working.',
      url: 'https://coingape.com/europe-stocks-rise-after-hitting-two-month-lows-amid-us-debt-deal/',
    },
  },
  {
    pageContent:
      'european stock markets opened higher friday morning as the us passed a bill to raise the debt ceiling and cap government spending for two years, averting a global economic catastrophe. jai pratap is a crypto and blockchain enthusiast with over three years of working experience with different major media houses. his current role at coingape includes creating high-impact web stories, cover breaking news, and write editorials. the debt ceiling bill passed the senate vote late thursday, after passing the house of representatives on wednesday. the uncertainty around the debt ceiling bill has only slightly rattled markets in the past month. now all eyes turn to the outlook for the u.s. economy, recession risk, and whether the federal reserve will raise, pause or even look at beginning to cut interest rates. european central bank president christine lagarde said inflation was still “too high” and that the hiking cycle needed to continue until it was clear inflation would come down to its 2% target in a “timely manner”. jai pratap also reads russian literature or watches some swedish movie when not working.',
    metadata: {
      chunk:
        'european stock markets opened higher friday morning as the us passed a bill to raise the debt ceiling and cap government spending for two years, averting a global economic catastrophe. jai pratap is a crypto and blockchain enthusiast with over three years of working experience with different major media houses. his current role at coingape includes creating high-impact web stories, cover breaking news, and write editorials. the debt ceiling bill passed the senate vote late thursday, after passing the house of representatives on wednesday. the uncertainty around the debt ceiling bill has only slightly rattled markets in the past month. now all eyes turn to the outlook for the u.s. economy, recession risk, and whether the federal reserve will raise, pause or even look at beginning to cut interest rates. european central bank president christine lagarde said inflation was still “too high” and that the hiking cycle needed to continue until it was clear inflation would come down to its 2% target in a “timely manner”. jai pratap also reads russian literature or watches some swedish movie when not working.',
      text: 'european stock markets opened higher friday morning as the us passed a bill to raise the debt ceiling and cap government spending for two years, averting a global economic catastrophe. jai pratap is a crypto and blockchain enthusiast with over three years of working experience with different major media houses. his current role at coingape includes creating high-impact web stories, cover breaking news, and write editorials. the debt ceiling bill passed the senate vote late thursday, after passing the house of representatives on wednesday. the uncertainty around the debt ceiling bill has only slightly rattled markets in the past month. now all eyes turn to the outlook for the u.s. economy, recession risk, and whether the federal reserve will raise, pause or even look at beginning to cut interest rates. european central bank president christine lagarde said inflation was still “too high” and that the hiking cycle needed to continue until it was clear inflation would come down to its 2% target in a “timely manner”. jai pratap also reads russian literature or watches some swedish movie when not working.',
      url: 'https://coingape.com/europe-stocks-rise-after-hitting-two-month-lows-amid-us-debt-deal/',
    },
  },
  {
    pageContent:
      'european stock markets opened higher friday morning as the us passed a bill to raise the debt ceiling and cap government spending for two years, averting a global economic catastrophe. jai pratap is a crypto and blockchain enthusiast with over three years of working experience with different major media houses. his current role at coingape includes creating high-impact web stories, cover breaking news, and write editorials. the debt ceiling bill passed the senate vote late thursday, after passing the house of representatives on wednesday. the uncertainty around the debt ceiling bill has only slightly rattled markets in the past month. now all eyes turn to the outlook for the u.s. economy, recession risk, and whether the federal reserve will raise, pause or even look at beginning to cut interest rates. european central bank president christine lagarde said inflation was still “too high” and that the hiking cycle needed to continue until it was clear inflation would come down to its 2% target in a “timely manner”. jai pratap also reads russian literature or watches some swedish movie when not working.',
    metadata: {
      chunk:
        'european stock markets opened higher friday morning as the us passed a bill to raise the debt ceiling and cap government spending for two years, averting a global economic catastrophe. jai pratap is a crypto and blockchain enthusiast with over three years of working experience with different major media houses. his current role at coingape includes creating high-impact web stories, cover breaking news, and write editorials. the debt ceiling bill passed the senate vote late thursday, after passing the house of representatives on wednesday. the uncertainty around the debt ceiling bill has only slightly rattled markets in the past month. now all eyes turn to the outlook for the u.s. economy, recession risk, and whether the federal reserve will raise, pause or even look at beginning to cut interest rates. european central bank president christine lagarde said inflation was still “too high” and that the hiking cycle needed to continue until it was clear inflation would come down to its 2% target in a “timely manner”. jai pratap also reads russian literature or watches some swedish movie when not working.',
      text: 'european stock markets opened higher friday morning as the us passed a bill to raise the debt ceiling and cap government spending for two years, averting a global economic catastrophe. jai pratap is a crypto and blockchain enthusiast with over three years of working experience with different major media houses. his current role at coingape includes creating high-impact web stories, cover breaking news, and write editorials. the debt ceiling bill passed the senate vote late thursday, after passing the house of representatives on wednesday. the uncertainty around the debt ceiling bill has only slightly rattled markets in the past month. now all eyes turn to the outlook for the u.s. economy, recession risk, and whether the federal reserve will raise, pause or even look at beginning to cut interest rates. european central bank president christine lagarde said inflation was still “too high” and that the hiking cycle needed to continue until it was clear inflation would come down to its 2% target in a “timely manner”. jai pratap also reads russian literature or watches some swedish movie when not working.',
      url: 'https://coingape.com/europe-stocks-rise-after-hitting-two-month-lows-amid-us-debt-deal/',
    },
  },
  {
    pageContent:
      "the us economy added 339,000 jobs in may, higher than economist forecasts of 195,000. the unemployment rate rose to 3.7% and average hourly earnings were up 0.3% in may versus april's 0.4%. the federal reserve has embarked on an historic string of rate hikes since early 2022 but the strong employment market has given them reason to continue tightening monetary policy. markets are divided on whether the fed will again boost rates and this switch in attitude has taken its toll on bitcoin, which tumbled from nearly $30,000 to the $27,000 level it was at just prior to this morning's data",
    metadata: {
      chunk:
        "the us economy added 339,000 jobs in may, higher than economist forecasts of 195,000. the unemployment rate rose to 3.7% and average hourly earnings were up 0.3% in may versus april's 0.4%. the federal reserve has embarked on an historic string of rate hikes since early 2022 but the strong employment market has given them reason to continue tightening monetary policy. markets are divided on whether the fed will again boost rates and this switch in attitude has taken its toll on bitcoin, which tumbled from nearly $30,000 to the $27,000 level it was at just prior to this morning's data",
      text: "the us economy added 339,000 jobs in may, higher than economist forecasts of 195,000. the unemployment rate rose to 3.7% and average hourly earnings were up 0.3% in may versus april's 0.4%. the federal reserve has embarked on an historic string of rate hikes since early 2022 but the strong employment market has given them reason to continue tightening monetary policy. markets are divided on whether the fed will again boost rates and this switch in attitude has taken its toll on bitcoin, which tumbled from nearly $30,000 to the $27,000 level it was at just prior to this morning's data",
      url: 'https://www.coindesk.com/business/2023/06/02/us-adds-339k-jobs-in-may-blowing-through-estimates-for-195k-bitcoin-steady-at-27k/',
    },
  },
];
